### PR TITLE
Image Assets

### PR DESCRIPTION
**Pull request by tomadamatkinson**
## Description

It is common to work with different image formats. Image assets represent images loaded from disk before they are converted into Vulkan images. This PR aims to simplify the image loading code from the framework v1.0 RAII loading mechanism to an ImageCodec, ImageLoader, and ImageWriter. Aided by the virtual filesystem, we can load from a file or from memory. 

Images are loaded into an ImageAsset. This represents an image as POD and will later be converted into a Vulkan Image using the Vulkan framework. With the use of Codecs, we can later optimize an asset pack for a particular platform or simply decode images when needed using a simple interface.

Each underlying third-party loader can be compiled separately - fast compile times in parallel :)

### CODE REVIEW

**Comment by tomadamatkinson** [comment]
@JoseEmilio-ARM @gpx1000 @gary-sweet @SaschaWillems @asuessenbach 

Finally sorted all the build issues and warnings as error issues in this PR. Please take a look when you have a chance

**Comment by SaschaWillems** [comment]
Quick question: Will this have any implications on how a sample loads/accesses the images, or is this a change "under the hood"?If it's the former, could you post a quick example on how a sample would need to be adjusted?

**Comment by SaschaWillems** [comment]
I'm having problems cloning this. When updating the submodules I get this for `tracy`:

```Failed to clone 'third_party/tracy'. Retry scheduled
BUG: submodule considered for cloning, doesn't need cloning any more?'```

Any ideas?

**Comment by SaschaWillems** [comment]
Wanted to give this a try, but it's not compiling for me on VS 2022 17.5 (latest). I'm getting multiple compile time errors:

```C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\wingdi.h(118,1): error C2220: Die folgende Warnung wird als Fehler behandelt.
C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\wingdi.h(118,1): warning C4005: "ERROR": Makro-Neudefinition
V:\Vulkan-KHR-Samples\Vulkan-Samples\components\common\include\components/common/error.hpp(61,1): message : Siehe vorherige Definition von "ERROR"
V:\Vulkan-KHR-Samples\Vulkan-Samples\components\vfs\src\std_filesystem.cpp(170,25): error C2440: "Initialisierung": "initializer list" kann nicht in "std::basic_string_view<char,std::char_traits<char>>" konvertiert werden
V:\Vulkan-KHR-Samples\Vulkan-Samples\components\vfs\src\std_filesystem.cpp(170,25): message : Quelltyp konnte von keinem Konstruktor angenommen werden, oder die Überladungsauflösung des Konstruktors ist mehrdeutig
V:\Vulkan-KHR-Samples\Vulkan-Samples\components\vfs\src\std_filesystem.cpp(206,25): error C2440: "Initialisierung": "initializer list" kann nicht in "std::basic_string_view<char,std::char_traits<char>>" konvertiert werden
V:\Vulkan-KHR-Samples\Vulkan-Samples\components\vfs\src\std_filesystem.cpp(206,25): message : Quelltyp konnte von keinem Konstruktor angenommen werden, oder die Überladungsauflösung des Konstruktors ist mehrdeutig
```

Sorry for the German errors, dunno how to get VS to output English errors.

But it looks like among other thing's it's having troubles finding a proper constructor in this place in `std_filesystem.cpp`:
image

It also treats a warning from `wingdi.h` as an error.

**Review by gpx1000 — APPROVED** [review]
Works here and I like the direction

**Comment by tomadamatkinson** [comment]
@SaschaWillems there is #634 to follow up on the platform-specific issues. I will merge this for now to make sure the development keeps momentum
