### PR TITLE
Remove unused PostProcessingComputePass

### LINKED ISSUE #841: framework/rendering/postprocessing_computepass is never used - should it be removed?
As the Title says.
Removing this class does not lead to any compile-time errors.

This class was introduced by #178, but was not used at that time. And it seems, it has never been used since.

### LINKED ISSUE #1570: PostProcessingComputePass: dangling iterators from get_resources() temporaries (found via clang 23 -Wdangling-gsl)
Building with clang 23 and warnings-as-errors fails in framework/rendering/postprocessing_computepass.cpp:

```
framework/rendering/postprocessing_computepass.cpp:154:33: error:
object backing the pointer will be destroyed at the end of the
full-expression [-Werror,-Wdangling-gsl]
```

Looking at the code, I think the warning is a true positive rather than noise. `PipelineLayout::get_resources()` returns
`const std::vector<ShaderResource>` by value (a fresh copy each call), and the transition code calls it three times:

```cpp
auto resource = std::find_if(pipeline_layout.get_resources().begin(),
                             pipeline_layout.get_resources().end(),
                             [&storage](const auto &res) { ... });
if (resource == pipeline_layout.get_resources().end())
    ...
const bool readable = !(resource->qualifiers & ...);
```

So `begin()` and `end()` come from two different temporary vectors, both are destroyed at the end of the statement, the later `end()`
comparison uses a third temporary, and `resource->qualifiers` dereferences an iterator into a destroyed vector.

It probably never crashes in practice because, as #841 noted, this class appears to be unused - but it is still compiled everywhere, so
clang 23 makes it a build failure for -Werror configurations. 

Two possible ways out:

1. Call get_resources() once and keep it in a local:

```cpp
const auto resources = pipeline_layout.get_resources();
auto resource = std::find_if(resources.begin(), resources.end(),
                             [&storage](const auto &res) { ... });
if (resource == resources.end())
```

or

2. remove the class, as #841 already suggested.

Happy to send a PR for option 1 if that is the preferred direction.

### PR DESCRIPTION
**Pull request by asuessenbach**
## Description

Build tested on Win11 with VS2026. Run tested on Win11 with NVidia GPU.

Fixes #1570
Fixes #841

## General Checklist:

Please ensure the following points are checked:

- [x] My code follows the [coding style](https://github.com/KhronosGroup/Vulkan-Samples/tree/main/CONTRIBUTING.adoc#Code-Style)
- [x] I have reviewed file [licenses](https://github.com/KhronosGroup/Vulkan-Samples/tree/main/CONTRIBUTING.adoc#Copyright-Notice-and-License-Template)
- [x] I have commented any added functions (in line with Doxygen)
- [x] I have commented any code that could be hard to understand
- [x] My changes do not add any new compiler warnings
- [x] My changes do not add any new validation layer errors or warnings
- [x] I have used existing framework/helper functions where possible
- [x] My changes do not add any regressions
- [x] I have tested every sample to ensure everything runs correctly
- [x] This PR describes the scope and expected impact of the changes I am making

 Note: The Samples CI runs a number of checks including:
 - [x] I have updated the header Copyright to reflect the current year (CI build will fail if Copyright is out of date)
 - [ ] My changes build on Windows, Linux, macOS and Android. Otherwise I have [documented any exceptions](https://github.com/KhronosGroup/Vulkan-Samples/tree/main/CONTRIBUTING.adoc#General-Requirements)

 If this PR contains framework changes:
 - [x] I did a full batch run using the `batch` command line argument to make sure all samples still work properly

## Sample Checklist

If your PR contains a new or modified sample, these further checks must be carried out *in addition* to the General Checklist:
- [ ] I have tested the sample on at least one compliant Vulkan implementation
- [ ] If the sample is vendor-specific, I have [tagged it appropriately](https://github.com/KhronosGroup/Vulkan-Samples/tree/main/CONTRIBUTING.adoc#General-Requirements)
- [ ] I have stated on what implementation the sample has been tested so that others can test on different implementations and platforms
- [ ] Any dependent assets have been merged and published in downstream modules
- [ ] For new samples, I have added a paragraph with a summary to the appropriate chapter in the readme of the folder that the sample belongs to [e.g. api samples readme](https://github.com/KhronosGroup/Vulkan-Samples/blob/main/samples/api/README.adoc)
- [ ] For new samples, I have added a tutorial README.md file to guide users through what they need to know to implement code using this feature. For example, see [conditional_rendering](https://github.com/KhronosGroup/Vulkan-Samples/tree/main/samples/extensions/conditional_rendering)
- [ ] For new samples, I have added a link to the [Antora navigation](https://github.com/KhronosGroup/Vulkan-Samples/blob/main/antora/modules/ROOT/nav.adoc) so that the sample will be listed at the Vulkan documentation site

### CODE REVIEW

**Comment by asuessenbach** [comment]
Clang Tidy Check is failing here as well. No idea why.

**Review by tomek-brcm — APPROVED** [review]
